### ISSUE TITLE
Investigate Gesture Sensor

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#18]
The SPIKE Prime Hub can recognize taps on the device. Maybe also the TechnicMediumHub since it exposes the internal device.

**Comment by tthiery** [comment]
Port Mode Info

````
  Port: 100
    IOTypeId: TechnicMediumHubGestSensor
    HardwareRevision: 0.0.0.1
    SoftwareRevision: 0.0.0.1
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: False
    LogicalSynchronizableCapability: False
    ModeCombinations: []
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: GEST
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 4
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 4
      Symbol:
      InputSupportsNull: False
      InputSupportFunctionalMapping20: True
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 1
      DatasetType: SByte
      TotalFigures: 1
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
````

Value is discrete and can be between 0 and 4. Which would conclude to 4-5 gestures. [SPIKE Prime specification](https://le-www-live-s.legocdn.com/sc/media/files/support/spike-prime/techspecs_techniclargehub-fba3b469ecb9eaafbde5f24d34ba090e.pdf) list 3 gestures: free fall, tap, shake. I rudimentary mapped them the following ... however .. the sensor emits many of them for the free fall and tapping is a pretty rough gesture. So that could be also crash or something.

````csharp
    public enum Gesture : int
    {
        None = 0, // UNSPECED
        Tap = 1, // UNSPECED
        Gesture_2 = 2,
        Shake = 3, // UNSPECED
        FreeFall = 4, // UNSPECED
    }
````
